deployment aangepast

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -22,6 +22,17 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y podman
 
+      - name: Install doctl if not present
+        run: |
+          if ! command -v doctl &> /dev/null; then
+          echo "doctl niet gevonden. Installeren..."
+          curl -L https://github.com/digitalocean/doctl/releases/download/v1.87.0/doctl-1.87.0-linux-amd64.tar.gz -o doctl.tar.gz
+          tar xzf doctl.tar.gz
+          sudo mv doctl /usr/local/bin/
+          else
+          echo "doctl is al geïnstalleerd. Installatie overslaan."
+          fi      
+
       - name: Log in to DigitalOcean Container Registry
         run: |
           echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | podman login registry.digitalocean.com --username ${{ secrets.DIGITALOCEAN_USERNAME }} --password-stdin
@@ -50,7 +61,6 @@ jobs:
           echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | podman login registry.digitalocean.com --username "oauth2" --password-stdin
           podman tag localhost/htmx-spring-boot:${{ env.IMAGE_TAG }} registry.digitalocean.com/cicdrych/htmx-spring-boot:${{ env.IMAGE_TAG }}
           podman push registry.digitalocean.com/cicdrych/htmx-spring-boot:${{ env.IMAGE_TAG }}
-  
   
 
   # Job 2: Deploy naar Kubernetes
@@ -91,17 +101,17 @@ jobs:
         run: |
           doctl kubernetes cluster kubeconfig save my-cluster     
 
-#      - name: Configure Kubernetes
-#        run: |
-#          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
-#          if [ ! -s kubeconfig ]; then
-#            echo "ERROR: Kubeconfig is leeg of verkeerd gedecodeerd!"
-#            exit 1
-#          fi
-#          mkdir -p ~/.kube
-#          mv kubeconfig ~/.kube/config
-#          chmod 600 ~/.kube/config
-#          export KUBECONFIG=~/.kube/config
+      #      - name: Configure Kubernetes
+      #        run: |
+      #          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
+      #          if [ ! -s kubeconfig ]; then
+      #            echo "ERROR: Kubeconfig is leeg of verkeerd gedecodeerd!"
+      #            exit 1
+      #          fi
+      #          mkdir -p ~/.kube
+      #          mv kubeconfig ~/.kube/config
+      #          chmod 600 ~/.kube/config
+      #          export KUBECONFIG=~/.kube/config
 
       #      - name: Debug Kubernetes Connection
       #        run: |
