URL logging als laatste stap

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -112,6 +112,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Installeren van de metric server met Helm indien dit nog niet is gebeurd
+        run: |
+          if ! helm list -n kube-system | grep -q metrics-server; then
+            echo "Metrics Server is niet gevonden. Installeren met Helm..."
+            helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
+            helm repo update
+            helm install metrics-server metrics-server/metrics-server -n kube-system
+          else
+            echo "Metrics Server is al succesvol geïnstalleerd."
+          fi
+
       - name: Installeren van de kubernetes command line indien dit nog niet is gebeurd
         run: |
           if kubectl version --client &> /dev/null; then
@@ -208,3 +219,18 @@ jobs:
         run: |
           kubectl apply -f kubernetes/deployment.yaml
           kubectl rollout restart deployment/htmx-spring-boot
+
+      - name: De URL om naar de applicatie te navigeren
+        run: |
+          echo "Haalt het externe IP adres op via de load balancer..."
+          APP_URL=$(kubectl get svc htmx-spring-boot-service -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
+
+          if [ -z "$APP_URL" ]; then
+            echo "ERROR: Helaas, geen extern IP adres gevonden voor de LoadBalancer!"
+            exit 1
+          fi
+
+          FULL_URL="http://$APP_URL"
+
+          echo "Application is beschikbaar op: $FULL_URL"
+          echo "::notice title=Application URL::$FULL_URL"
